return {
  settings = {
    gopls = {
      completeUnimported = true,
      usePlaceholders = true,
      gofumpt = true,
      staticcheck = true,
      semanticTokens = true,
      directoryFilters = { "-.git", "-node_modules", "-vendor" },
      analyses = {
        unusedparams = true,
        unusedwrite = true,
        unreachable = true,
        nilness = true,
        shadow = true,
        useany = true,
        fieldalignment = false,
      },
      hints = {
        assignVariableTypes = true,
        compositeLiteralFields = true,
        compositeLiteralTypes = true,
        constantValues = true,
        functionTypeParameters = true,
        parameterNames = true,
        rangeVariableTypes = true,
      },
      codelenses = {
        gc_details = false,
        generate = true,
        regenerate_cgo = true,
        run_govulncheck = true,
        test = true,
        tidy = true,
        upgrade_dependency = true,
        vendor = true,
      },
    },
  },
}
