# Install with: brew bundle --file Brewfile

# Shell and terminal workflow
brew "atuin"
brew "bash"
brew "bat"
brew "btop"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "herdr"
brew "tree"
brew "vhs"
brew "wget"
brew "yq"
brew "zoxide"

# Development and AI tools
brew "act"
brew "cue"
brew "go@1.25"
brew "golangci-lint"
brew "node"
brew "nvm"
brew "opencode"
brew "pnpm@10"
brew "python@3.14"
brew "rust"
brew "uv"

# Git, cloud, and Kubernetes
brew "awscli"
brew "gh"
brew "googleworkspace-cli"
brew "gum"
brew "helm"
brew "helmfile"
brew "k9s"
brew "kubectl"
brew "kustomize"
brew "lazygit"
brew "stern"
brew "terraform"
brew "tfenv"

# Work machine only
brew "azure-cli"
brew "kubelogin"

# macOS applications
cask "aerospace"
cask "codex"
cask "flameshot"
cask "font-jetbrains-mono-nerd-font"
cask "gcloud-cli"
cask "ghostty"
