after-login-command = []
after-startup-command = []
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true 
[key-mapping]
    preset = 'qwerty'
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0
[mode.main.binding]
    alt-w = 'layout tiles horizontal vertical'
    alt-s = 'layout accordion vertical'
    alt-f = 'fullscreen'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
  
    alt-shift-right = 'move-node-to-monitor --focus-follows-window right'
    alt-shift-left  = 'move-node-to-monitor --focus-follows-window left'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1' #Term
    alt-2 = 'workspace 2' #Browser
    alt-3 = 'workspace 3' #Social
    alt-4 = 'workspace 4' #Music,Video
    alt-5 = 'workspace 5' #Productivity
    alt-6 = 'workspace 6' #Random

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-space = 'layout floating tiling'

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty" # term
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.google.Chrome" # Browser
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.spotify.client" # Music
run = "move-node-to-workspace 4" 

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap" # Slack
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "com.microsoft.teams2" # Teams
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "md.obsidian" # Obsidian
run = "move-node-to-workspace 5" 

[[on-window-detected]]
if.app-id = "mcom.todoist.mac.Todois" # Todoist
run = "move-node-to-workspace 5" 
