format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$helm\
$cmd_duration\
$fill\
$terraform\
$golang\
$python\
$nodejs\
$rust\
$lua\
$aws\
$status\
\n$character
"""

add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[hostname]
ssh_only = true

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

[fill]
symbol = " "

[aws]
format = "[$symbol($profile )]($style)"
symbol = "☁ "
style = "bold yellow"
force_display = false

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "!"
staged = '[++\($count\)](green)'
renamed = "»"
deleted = "✘"

[golang]
symbol = " "
format = '[$symbol($version )]($style)'

[python]
pyenv_version_name = false
symbol = " "
format = '[$symbol($version )]($style)'
detect_extensions = ["py"]

[ruby]
symbol = " "
detect_files = ["Gemfile", ".ruby-version"]
style = "bold red"
format = "[$symbol($version )]($style)"
detect_variables = []

[terraform]
symbol = "⬡ "
format = '[$symbol($version )]($style)'
disabled = false
detect_folders = ['.terraform']

[nodejs]
symbol = ' '
format = '[$symbol($version )](bold green)'
disabled = false
detect_files = ['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']

[rust]
symbol = " "
format = '[$symbol($version )](red bold)'

[lua]
symbol = " "
format = '[$symbol($version )](bold white)'

[kubernetes]
symbol = "☸ "
format = '[$symbol$context](dimmed green) '
disabled = false
detect_files = []

[helm]
symbol = "⎈ "
format = '[$symbol($version )](bold white)'

[status]
disabled = false
format = '[$status]($style) '
style = "bold red"

