#!/bin/sh

clone_url="ssh://git@git-ssh.local.net:2222/mvaldes/wiki.git"

# clone/update repository
if [ -d ~/wiki ]; then
	cd ~/wiki && git pull
else
	echo 'First run detected. Cloning repo...'
	git clone "$clone_url" ~/wiki
fi

# open the editor in the root vimwiki
nvim ~/wiki/

# if file changed, save & commit changes & push
if ! (cd ~/wiki && git diff-index --quiet HEAD --); then
	echo "Changes detected"
  (cd ~/wiki && git add --all && git commit -m '[Automated Commit]' && git push)
fi
